spring:
  redis:
    host: 127.0.0.1
    port: 6379

  rabbitmq:
    host: 192.168.1.222
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true  #消息确认
    publisher-returns: true   #消息返回
    virtual-host: /
    connection-timeout: 15000
    template:
      mandatory: true #消息不可达，
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 1

#  thymeleaf:
#    cache: false
#    mode: LEGACYHTML5

